package com.product_backend.product_backend.models;

import javax.validation.constraints.NotNull;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Table(name = "products")
public class Product {

    // TODO check if it can be assign instead of autogenerated
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Long id;

    @Column(name = "code")
    @NotNull
    private String code;

    @Column(name = "name")
    @NotNull
    private String name;

    @Column(name = "description")
    @NotNull
    private String description;

    @Column(name = "price")
    @NotNull
    private Float price;

    @Column(name = "quantity")
    @NotNull
    private Integer quantity;

    @Column(name = "inventoryStatus")
    @NotNull
    private String inventoryStatus;

    @Column(name = "category")
    @NotNull
    private String category;

    @Column(name = "image")
    private String image;

    @Column(name = "rating")
    private Float rating;

    // TODO toString
}
